/**
 * 智能水处理系统设计平台 v4.0 — 类型定义
 */

import { WaterQualityParams } from '@/lib/constants/water-quality';
import { ProcessUnit } from '@/components/process-design';
import type { LucideIcon } from 'lucide-react';

// ==================== 水质参数类型 ====================

export interface WaterQualityInput {
  inletWaterQuality: WaterQualityParams;
  outletWaterQuality: Partial<WaterQualityParams>;
  targetOutletQuality: Partial<WaterQualityParams>;
}

// ==================== 设计流量类型 ====================

export interface DesignFlow {
  feed: number;      // 进水量 (m³/h)
  permeate: number;  // 产水量 (m³/h)
  recovery: number;  // 回收率 (%)
}

// ==================== 水泵配置类型 ====================

export interface PumpConfig {
  feedPump: string;
  highPressurePump: string;
  interstagePump: string;
  ufPump: string;
}

// ==================== 模拟结果类型（匹配 filter-effect API 真实响应）====================

export interface ROStageResult {
  stageIndex: number;
  feedFlow: number;
  feedTDS: number;
  feedPressure: number;
  stageRecovery: number;
  permeateFlow: number;
  permeateTDS: number;
  concentrateFlow: number;
  concentrateTDS: number;
  avgFlux: number;
  rejection: number;
  pressureDrop: number;
}

export interface SimulationStep {
  step: number;
  unit: string;
  unitType: string;
  inlet: Record<string, number>;
  outlet: Record<string, number>;
  removalRates: Record<string, string>;
  notes: string;
  formula?: string;
  stageResults?: ROStageResult[];
}

export interface SimulationStatistics {
  totalTDSRemoval: string;
  totalTurbidityRemoval: string;
  totalCODRemoval: string;
  totalHardnessRemoval: string;
  inletTDS: number;
  outletTDS: number;
  processSteps: number;
}

export interface TargetAchievement {
  target: number;
  actual: number;
  achieved: boolean;
}

export interface TargetAssessment {
  meetsTarget: boolean;
  target: Partial<WaterQualityParams>;
  autoGenerated: boolean;
  recommendedStandards: Array<{
    id: string;
    name: string;
    description: string;
    standards: Record<string, number>;
    typicalApplication: string;
  }>;
  achievement: {
    tds: TargetAchievement;
    turbidity: TargetAchievement;
    cod: TargetAchievement;
  };
}

export interface FoulingRiskFactor {
  name: string;
  risk: 'low' | 'medium' | 'high';
  description: string;
}

export interface FoulingRisk {
  overallRisk: 'low' | 'medium' | 'high';
  factors: FoulingRiskFactor[];
  recommendations: string[];
}

export interface ComplianceEntry {
  standardId: string;
  standardName: string;
  typicalApplication?: string;
  issues?: string[];
}

export interface ComplianceAssessment {
  fullyCompliant: ComplianceEntry[];
  partiallyCompliant: ComplianceEntry[];
  summary: string;
}

export interface DesignParams {
  feedFlow: number;
  permeateFlow: number;
  recovery: number;
  temperature: number;
}

/** 匹配 /api/simulation/filter-effect 的真实响应结构 */
export interface SimulationResult {
  success: boolean;
  simulation: SimulationStep[];
  finalWater: Record<string, number>;
  statistics: SimulationStatistics;
  targetAssessment: TargetAssessment;
  issues: string[];
  recommendations: string[];
  foulingRisk: FoulingRisk | null;
  concentrateWater: Record<string, number> | null;
  complianceAssessment: ComplianceAssessment;
  designParams: DesignParams;
  aiAnalysis?: string;
  error?: string;
}

// ==================== API 响应类型 ====================

export interface APIResponse<T> {
  success: boolean;
  data?: T;
  error?: string;
  message?: string;
}

export interface WaterQualityParseResponse {
  success: boolean;
  data: Partial<WaterQualityParams>;
  missingParams: string[];
  analysis: string;
}

export interface WaterQualityAnalyzeResponse {
  success: boolean;
  analysis: string;
  classification: {
    type: string;
    tdsLevel: string;
    hardnessLevel: string;
    warnings: string[];
    suitability: string;
  };
  membraneRecommendation: unknown;
  limitChecks: Array<{
    param: string;
    value: number;
    limit: number;
    status: 'pass' | 'warning' | 'fail';
    message: string;
  }>;
}

export interface MembraneDesign {
  brand: string;
  model: string;
  category: string;
  elements: number;
  vessels: number;
  stages: number;
  flux: number;
}

export interface PumpDesign {
  model: string;
  brand: string;
  flow: number;
  head: number;
  power: number;
}

export interface EquipmentItem {
  name: string;
  model: string;
  quantity: number;
  unit: string;
  spec: string;
}

export interface DesignGenerateResponse {
  success: boolean;
  design: {
    membranes: {
      ro: MembraneDesign | null;
      uf: MembraneDesign | null;
    };
    pumps: {
      feedPump: PumpDesign | null;
      highPressurePump: PumpDesign | null;
      interstagePump?: PumpDesign | null;
    };
    processFlow: string[];
    equipmentList: EquipmentItem[];
    operatingParams: Record<string, number | string>;
  };
}

// ==================== 组件 Props 类型 ====================

export interface WaterQualityInputProps {
  inletWaterQuality: WaterQualityParams;
  outletWaterQuality: Partial<WaterQualityParams>;
  onInletWaterQualityChange: (params: WaterQualityParams) => void;
  onOutletWaterQualityChange: (params: Partial<WaterQualityParams>) => void;
  designFlow: DesignFlow;
  onDesignFlowChange: (flow: DesignFlow) => void;
  targetOutletQuality: Partial<WaterQualityParams>;
  onTargetOutletQualityChange: (params: Partial<WaterQualityParams>) => void;
}

export interface ProcessDesignProps {
  processUnits: ProcessUnit[];
  onProcessUnitsChange: (units: ProcessUnit[]) => void;
  designFlow: DesignFlow;
  onDesignFlowChange: (flow: DesignFlow) => void;
  inletWaterQuality: WaterQualityParams;
  outletTargetQuality: Partial<WaterQualityParams>;
}

export interface ProcessConfig {
  pretreatment: string;
  precisionFilter: string;
  ufSystem: string;
  mainProcess: string;
}

export interface MembraneConfig {
  roBrand: string;
  roModel: string;
  roCategory: string;
  ufModel: string;
  ufBrand: string;
  stages: number;
  elementsPerVessel: number;
  vesselsStage1: number;
  vesselsStage2: number;
  vesselsStage3: number;
  totalElements: number;
  totalVessels: number;
  recovery: number;
  flux: number;
}

export interface PumpSelectionProps {
  designFlow: DesignFlow;
  processUnits: ProcessUnit[];
  pumpConfig: PumpConfig;
  onPumpConfigChange: (config: PumpConfig) => void;
  waterQuality: WaterQualityParams;
}

export interface SimulationResultViewProps {
  result: SimulationResult | null;
  isSimulating: boolean;
  onSimulate: (retryCount?: number) => Promise<void>;
  inletWaterQuality: WaterQualityParams;
  outletTargetQuality: Partial<WaterQualityParams>;
  pumpConfig: PumpConfig;
  designFlow: DesignFlow;
  waterQuality: WaterQualityParams;
  processUnits: ProcessUnit[];
}

export interface DesignSummaryProps {
  waterQuality: WaterQualityParams;
  designFlow: DesignFlow;
  processConfig: ProcessConfig;
  membraneConfig: MembraneConfig;
  pumpConfig: PumpConfig;
  designResult: SimulationResult | null;
  processUnits: ProcessUnit[];
}

// ==================== 步进向导类型 ====================

export interface Step {
  label: string;
  icon: LucideIcon;
}
